"""
Application Constants
=====================
Crop metadata, soil parameters, season data, and other domain-specific constants.
"""

# ── Crop Metadata ────────────────────────────────────────────────────────
# Comprehensive data for all crops in the recommendation system
CROP_DATABASE = {
    "rice": {
        "name": "Rice",
        "duration_days": 120,
        "season": "Kharif",
        "water_req_mm": 1200,
        "irrigation_method": "Flood / Paddy Irrigation",
        "irrigation_freq": "Continuous standing water",
        "fertilizer_n": 120,
        "fertilizer_p": 60,
        "fertilizer_k": 40,
        "yield_tonnes_per_ha": 4.5,
        "production_cost_per_ha": 45000,
        "market_price_per_quintal": 2040,
        "market_demand": "High",
        "suitable_soil": ["Clay Soil", "Loamy Soil", "Black Soil"],
    },
    "wheat": {
        "name": "Wheat",
        "duration_days": 135,
        "season": "Rabi",
        "water_req_mm": 450,
        "irrigation_method": "Sprinkler / Flood",
        "irrigation_freq": "Every 20-25 days",
        "fertilizer_n": 120,
        "fertilizer_p": 60,
        "fertilizer_k": 40,
        "yield_tonnes_per_ha": 3.5,
        "production_cost_per_ha": 35000,
        "market_price_per_quintal": 2125,
        "market_demand": "High",
        "suitable_soil": ["Loamy Soil", "Clay Soil", "Black Soil"],
    },
    "maize": {
        "name": "Maize",
        "duration_days": 100,
        "season": "Kharif / Rabi",
        "water_req_mm": 500,
        "irrigation_method": "Drip / Furrow",
        "irrigation_freq": "Every 7-10 days",
        "fertilizer_n": 150,
        "fertilizer_p": 75,
        "fertilizer_k": 40,
        "yield_tonnes_per_ha": 5.0,
        "production_cost_per_ha": 30000,
        "market_price_per_quintal": 1962,
        "market_demand": "High",
        "suitable_soil": ["Loamy Soil", "Sandy Soil", "Red Soil"],
    },
    "cotton": {
        "name": "Cotton",
        "duration_days": 180,
        "season": "Kharif",
        "water_req_mm": 700,
        "irrigation_method": "Drip",
        "irrigation_freq": "Every 7-10 days",
        "fertilizer_n": 100,
        "fertilizer_p": 50,
        "fertilizer_k": 50,
        "yield_tonnes_per_ha": 2.0,
        "production_cost_per_ha": 50000,
        "market_price_per_quintal": 6620,
        "market_demand": "High",
        "suitable_soil": ["Black Soil", "Loamy Soil"],
    },
    "jute": {
        "name": "Jute",
        "duration_days": 120,
        "season": "Kharif",
        "water_req_mm": 800,
        "irrigation_method": "Flood",
        "irrigation_freq": "Every 5-7 days",
        "fertilizer_n": 60,
        "fertilizer_p": 30,
        "fertilizer_k": 30,
        "yield_tonnes_per_ha": 2.5,
        "production_cost_per_ha": 25000,
        "market_price_per_quintal": 4750,
        "market_demand": "Medium",
        "suitable_soil": ["Loamy Soil", "Clay Soil"],
    },
    "coconut": {
        "name": "Coconut",
        "duration_days": 365,
        "season": "Perennial",
        "water_req_mm": 1500,
        "irrigation_method": "Drip / Basin",
        "irrigation_freq": "Every 3-4 days",
        "fertilizer_n": 170,
        "fertilizer_p": 85,
        "fertilizer_k": 170,
        "yield_tonnes_per_ha": 10.0,
        "production_cost_per_ha": 60000,
        "market_price_per_quintal": 2500,
        "market_demand": "High",
        "suitable_soil": ["Sandy Soil", "Laterite Soil", "Loamy Soil"],
    },
    "papaya": {
        "name": "Papaya",
        "duration_days": 300,
        "season": "Year-round",
        "water_req_mm": 1000,
        "irrigation_method": "Drip",
        "irrigation_freq": "Every 3-4 days",
        "fertilizer_n": 200,
        "fertilizer_p": 200,
        "fertilizer_k": 250,
        "yield_tonnes_per_ha": 40.0,
        "production_cost_per_ha": 80000,
        "market_price_per_quintal": 1200,
        "market_demand": "Medium",
        "suitable_soil": ["Loamy Soil", "Sandy Soil"],
    },
    "orange": {
        "name": "Orange",
        "duration_days": 365,
        "season": "Perennial",
        "water_req_mm": 900,
        "irrigation_method": "Drip",
        "irrigation_freq": "Every 5-7 days",
        "fertilizer_n": 600,
        "fertilizer_p": 200,
        "fertilizer_k": 200,
        "yield_tonnes_per_ha": 15.0,
        "production_cost_per_ha": 70000,
        "market_price_per_quintal": 3000,
        "market_demand": "High",
        "suitable_soil": ["Loamy Soil", "Red Soil"],
    },
    "apple": {
        "name": "Apple",
        "duration_days": 365,
        "season": "Perennial",
        "water_req_mm": 800,
        "irrigation_method": "Drip",
        "irrigation_freq": "Every 5-7 days",
        "fertilizer_n": 350,
        "fertilizer_p": 175,
        "fertilizer_k": 350,
        "yield_tonnes_per_ha": 12.0,
        "production_cost_per_ha": 100000,
        "market_price_per_quintal": 5000,
        "market_demand": "High",
        "suitable_soil": ["Loamy Soil"],
    },
    "muskmelon": {
        "name": "Muskmelon",
        "duration_days": 90,
        "season": "Summer",
        "water_req_mm": 400,
        "irrigation_method": "Drip",
        "irrigation_freq": "Every 2-3 days",
        "fertilizer_n": 100,
        "fertilizer_p": 60,
        "fertilizer_k": 60,
        "yield_tonnes_per_ha": 15.0,
        "production_cost_per_ha": 40000,
        "market_price_per_quintal": 1500,
        "market_demand": "Medium",
        "suitable_soil": ["Sandy Soil", "Loamy Soil"],
    },
    "watermelon": {
        "name": "Watermelon",
        "duration_days": 90,
        "season": "Summer",
        "water_req_mm": 500,
        "irrigation_method": "Drip / Furrow",
        "irrigation_freq": "Every 3-4 days",
        "fertilizer_n": 100,
        "fertilizer_p": 50,
        "fertilizer_k": 50,
        "yield_tonnes_per_ha": 25.0,
        "production_cost_per_ha": 35000,
        "market_price_per_quintal": 800,
        "market_demand": "Medium",
        "suitable_soil": ["Sandy Soil", "Loamy Soil"],
    },
    "grapes": {
        "name": "Grapes",
        "duration_days": 365,
        "season": "Perennial",
        "water_req_mm": 600,
        "irrigation_method": "Drip",
        "irrigation_freq": "Every 3-5 days",
        "fertilizer_n": 200,
        "fertilizer_p": 100,
        "fertilizer_k": 200,
        "yield_tonnes_per_ha": 20.0,
        "production_cost_per_ha": 150000,
        "market_price_per_quintal": 4000,
        "market_demand": "High",
        "suitable_soil": ["Sandy Soil", "Loamy Soil", "Red Soil"],
    },
    "mango": {
        "name": "Mango",
        "duration_days": 365,
        "season": "Perennial",
        "water_req_mm": 900,
        "irrigation_method": "Drip / Basin",
        "irrigation_freq": "Every 7-10 days",
        "fertilizer_n": 500,
        "fertilizer_p": 250,
        "fertilizer_k": 500,
        "yield_tonnes_per_ha": 8.0,
        "production_cost_per_ha": 80000,
        "market_price_per_quintal": 4500,
        "market_demand": "High",
        "suitable_soil": ["Loamy Soil", "Red Soil", "Laterite Soil"],
    },
    "banana": {
        "name": "Banana",
        "duration_days": 330,
        "season": "Year-round",
        "water_req_mm": 1800,
        "irrigation_method": "Drip",
        "irrigation_freq": "Every 2-3 days",
        "fertilizer_n": 200,
        "fertilizer_p": 60,
        "fertilizer_k": 300,
        "yield_tonnes_per_ha": 30.0,
        "production_cost_per_ha": 90000,
        "market_price_per_quintal": 1200,
        "market_demand": "High",
        "suitable_soil": ["Loamy Soil", "Clay Soil"],
    },
    "pomegranate": {
        "name": "Pomegranate",
        "duration_days": 365,
        "season": "Perennial",
        "water_req_mm": 500,
        "irrigation_method": "Drip",
        "irrigation_freq": "Every 5-7 days",
        "fertilizer_n": 250,
        "fertilizer_p": 125,
        "fertilizer_k": 125,
        "yield_tonnes_per_ha": 12.0,
        "production_cost_per_ha": 100000,
        "market_price_per_quintal": 5000,
        "market_demand": "High",
        "suitable_soil": ["Sandy Soil", "Loamy Soil", "Black Soil"],
    },
    "lentil": {
        "name": "Lentil",
        "duration_days": 110,
        "season": "Rabi",
        "water_req_mm": 250,
        "irrigation_method": "Sprinkler",
        "irrigation_freq": "Every 15-20 days",
        "fertilizer_n": 20,
        "fertilizer_p": 40,
        "fertilizer_k": 20,
        "yield_tonnes_per_ha": 1.2,
        "production_cost_per_ha": 22000,
        "market_price_per_quintal": 5500,
        "market_demand": "Medium",
        "suitable_soil": ["Loamy Soil", "Clay Soil"],
    },
    "blackgram": {
        "name": "Blackgram",
        "duration_days": 90,
        "season": "Kharif / Rabi",
        "water_req_mm": 300,
        "irrigation_method": "Sprinkler",
        "irrigation_freq": "Every 10-15 days",
        "fertilizer_n": 20,
        "fertilizer_p": 40,
        "fertilizer_k": 20,
        "yield_tonnes_per_ha": 0.8,
        "production_cost_per_ha": 20000,
        "market_price_per_quintal": 6000,
        "market_demand": "Medium",
        "suitable_soil": ["Black Soil", "Loamy Soil", "Red Soil"],
    },
    "mungbean": {
        "name": "Mungbean",
        "duration_days": 75,
        "season": "Kharif / Summer",
        "water_req_mm": 250,
        "irrigation_method": "Sprinkler",
        "irrigation_freq": "Every 10-12 days",
        "fertilizer_n": 20,
        "fertilizer_p": 40,
        "fertilizer_k": 20,
        "yield_tonnes_per_ha": 0.8,
        "production_cost_per_ha": 18000,
        "market_price_per_quintal": 7275,
        "market_demand": "Medium",
        "suitable_soil": ["Loamy Soil", "Sandy Soil"],
    },
    "mothbeans": {
        "name": "Moth Beans",
        "duration_days": 75,
        "season": "Kharif",
        "water_req_mm": 200,
        "irrigation_method": "Sprinkler",
        "irrigation_freq": "Every 15-20 days",
        "fertilizer_n": 15,
        "fertilizer_p": 30,
        "fertilizer_k": 15,
        "yield_tonnes_per_ha": 0.5,
        "production_cost_per_ha": 15000,
        "market_price_per_quintal": 5800,
        "market_demand": "Low",
        "suitable_soil": ["Sandy Soil", "Red Soil"],
    },
    "pigeonpeas": {
        "name": "Pigeon Peas",
        "duration_days": 160,
        "season": "Kharif",
        "water_req_mm": 350,
        "irrigation_method": "Sprinkler",
        "irrigation_freq": "Every 10-15 days",
        "fertilizer_n": 20,
        "fertilizer_p": 50,
        "fertilizer_k": 20,
        "yield_tonnes_per_ha": 1.0,
        "production_cost_per_ha": 25000,
        "market_price_per_quintal": 6600,
        "market_demand": "Medium",
        "suitable_soil": ["Black Soil", "Red Soil", "Loamy Soil"],
    },
    "kidneybeans": {
        "name": "Kidney Beans",
        "duration_days": 120,
        "season": "Kharif",
        "water_req_mm": 400,
        "irrigation_method": "Sprinkler",
        "irrigation_freq": "Every 7-10 days",
        "fertilizer_n": 50,
        "fertilizer_p": 80,
        "fertilizer_k": 40,
        "yield_tonnes_per_ha": 1.5,
        "production_cost_per_ha": 30000,
        "market_price_per_quintal": 8000,
        "market_demand": "Medium",
        "suitable_soil": ["Loamy Soil", "Clay Soil"],
    },
    "chickpea": {
        "name": "Chickpea",
        "duration_days": 110,
        "season": "Rabi",
        "water_req_mm": 250,
        "irrigation_method": "Sprinkler",
        "irrigation_freq": "Every 15-20 days",
        "fertilizer_n": 20,
        "fertilizer_p": 50,
        "fertilizer_k": 20,
        "yield_tonnes_per_ha": 1.2,
        "production_cost_per_ha": 25000,
        "market_price_per_quintal": 5230,
        "market_demand": "High",
        "suitable_soil": ["Black Soil", "Loamy Soil"],
    },
    "coffee": {
        "name": "Coffee",
        "duration_days": 365,
        "season": "Perennial",
        "water_req_mm": 1500,
        "irrigation_method": "Drip",
        "irrigation_freq": "Every 5-7 days",
        "fertilizer_n": 160,
        "fertilizer_p": 80,
        "fertilizer_k": 160,
        "yield_tonnes_per_ha": 1.0,
        "production_cost_per_ha": 120000,
        "market_price_per_quintal": 25000,
        "market_demand": "High",
        "suitable_soil": ["Laterite Soil", "Loamy Soil", "Red Soil"],
    },
}


# ── Fertilizer Database ──────────────────────────────────────────────────
FERTILIZER_DATABASE = {
    "organic": [
        {
            "name": "Farm Yard Manure (FYM)",
            "type": "Organic",
            "npk_ratio": "0.5-0.2-0.5",
            "application_method": "Broadcast before plowing",
            "cost_per_kg": 3,
            "benefit": "Improves soil structure, water retention, and microbial activity",
        },
        {
            "name": "Vermicompost",
            "type": "Organic",
            "npk_ratio": "1.5-0.5-1.0",
            "application_method": "Mix with soil near root zone",
            "cost_per_kg": 8,
            "benefit": "Rich in nutrients, improves soil aeration and drainage",
        },
        {
            "name": "Neem Cake",
            "type": "Organic",
            "npk_ratio": "5.0-1.0-1.5",
            "application_method": "Incorporate into soil before sowing",
            "cost_per_kg": 20,
            "benefit": "Natural pest repellent, slow-release nitrogen",
        },
        {
            "name": "Green Manure (Dhaincha/Sesbania)",
            "type": "Organic",
            "npk_ratio": "2.0-0.5-1.5",
            "application_method": "Grow and plow into soil 45 days before planting",
            "cost_per_kg": 0,
            "benefit": "Fixes atmospheric nitrogen, adds organic matter",
        },
    ],
    "chemical": [
        {
            "name": "Urea (46-0-0)",
            "type": "Chemical",
            "npk_ratio": "46-0-0",
            "application_method": "Top dressing, split application",
            "cost_per_kg": 6,
            "benefit": "High nitrogen for vegetative growth",
        },
        {
            "name": "DAP (18-46-0)",
            "type": "Chemical",
            "npk_ratio": "18-46-0",
            "application_method": "Basal application at sowing",
            "cost_per_kg": 27,
            "benefit": "Phosphorus for root development and flowering",
        },
        {
            "name": "MOP (0-0-60)",
            "type": "Chemical",
            "npk_ratio": "0-0-60",
            "application_method": "Basal or split application",
            "cost_per_kg": 18,
            "benefit": "Potassium for disease resistance and fruit quality",
        },
        {
            "name": "NPK Complex (10-26-26)",
            "type": "Chemical",
            "npk_ratio": "10-26-26",
            "application_method": "Basal application",
            "cost_per_kg": 28,
            "benefit": "Balanced nutrition for overall crop growth",
        },
        {
            "name": "SSP (0-16-0)",
            "type": "Chemical",
            "npk_ratio": "0-16-0",
            "application_method": "Basal application at sowing",
            "cost_per_kg": 8,
            "benefit": "Phosphorus with calcium and sulphur",
        },
    ],
    "bio": [
        {
            "name": "Rhizobium",
            "type": "Bio-Fertilizer",
            "npk_ratio": "N-fixer",
            "application_method": "Seed treatment before sowing",
            "cost_per_kg": 50,
            "benefit": "Fixes atmospheric nitrogen for legumes",
        },
        {
            "name": "Azospirillum",
            "type": "Bio-Fertilizer",
            "npk_ratio": "N-fixer",
            "application_method": "Soil application or seedling dip",
            "cost_per_kg": 50,
            "benefit": "Fixes nitrogen for non-legume crops like rice, wheat",
        },
        {
            "name": "PSB (Phosphorus Solubilizing Bacteria)",
            "type": "Bio-Fertilizer",
            "npk_ratio": "P-solubilizer",
            "application_method": "Soil application with FYM",
            "cost_per_kg": 50,
            "benefit": "Makes soil phosphorus available to plants",
        },
        {
            "name": "Trichoderma",
            "type": "Bio-Fertilizer",
            "npk_ratio": "Bio-control",
            "application_method": "Soil application or seed treatment",
            "cost_per_kg": 80,
            "benefit": "Prevents soil-borne diseases, promotes root growth",
        },
    ],
}


# ── Disease Database ─────────────────────────────────────────────────────
DISEASE_DATABASE = {
    "Tomato___Bacterial_spot": {
        "disease": "Bacterial Spot",
        "crop": "Tomato",
        "cause": "Xanthomonas bacteria, spread through rain splash and contaminated seeds",
        "severity_levels": {"Low": "Few spots on leaves", "Medium": "Multiple spots, some defoliation", "High": "Extensive spotting, fruit lesions"},
        "organic_treatment": "Apply copper-based organic sprays. Remove and destroy infected leaves. Use disease-free seeds.",
        "chemical_treatment": "Spray Copper Oxychloride (3g/L) or Streptomycin Sulphate (0.5g/L).",
        "prevention": "Use disease-resistant varieties, avoid overhead irrigation, maintain crop rotation.",
        "recovery_time": "2-3 weeks with proper treatment",
    },
    "Tomato___Late_blight": {
        "disease": "Late Blight",
        "crop": "Tomato",
        "cause": "Phytophthora infestans fungus, favored by cool wet conditions",
        "severity_levels": {"Low": "Small dark spots", "Medium": "Large water-soaked lesions", "High": "Rapid plant death"},
        "organic_treatment": "Apply Bordeaux mixture (1%). Remove and burn affected plants.",
        "chemical_treatment": "Spray Mancozeb (2.5g/L) or Metalaxyl + Mancozeb (2.5g/L).",
        "prevention": "Avoid dense planting, improve air circulation, use resistant varieties.",
        "recovery_time": "3-4 weeks if caught early",
    },
    "Tomato___Early_blight": {
        "disease": "Early Blight",
        "crop": "Tomato",
        "cause": "Alternaria solani fungus, spread by wind and rain",
        "severity_levels": {"Low": "Concentric ring spots on lower leaves", "Medium": "Significant defoliation", "High": "Severe leaf loss, fruit damage"},
        "organic_treatment": "Apply neem oil (5ml/L). Remove infected leaves. Mulch around plants.",
        "chemical_treatment": "Spray Chlorothalonil (2g/L) or Mancozeb (2.5g/L).",
        "prevention": "Practice crop rotation, stake plants for air flow, avoid wet foliage.",
        "recovery_time": "2-3 weeks",
    },
    "Potato___Late_blight": {
        "disease": "Late Blight",
        "crop": "Potato",
        "cause": "Phytophthora infestans, cool humid conditions",
        "severity_levels": {"Low": "Dark spots on leaves", "Medium": "White mold on undersides", "High": "Tuber rot, complete plant death"},
        "organic_treatment": "Bordeaux mixture spray. Destroy infected plants immediately.",
        "chemical_treatment": "Spray Cymoxanil + Mancozeb (3g/L) preventively.",
        "prevention": "Use certified seed potatoes, avoid excess moisture, hill up soil.",
        "recovery_time": "Difficult to recover in severe cases. 3-4 weeks if mild.",
    },
    "Potato___Early_blight": {
        "disease": "Early Blight",
        "crop": "Potato",
        "cause": "Alternaria solani, warm humid conditions",
        "severity_levels": {"Low": "Small dark spots", "Medium": "Concentric rings, yellowing", "High": "Defoliation, tuber lesions"},
        "organic_treatment": "Neem oil spray. Remove lower affected leaves. Add mulch.",
        "chemical_treatment": "Spray Mancozeb (2.5g/L) or Chlorothalonil (2g/L).",
        "prevention": "Crop rotation, adequate spacing, avoid overhead irrigation.",
        "recovery_time": "2-3 weeks",
    },
    "Corn___Common_rust": {
        "disease": "Common Rust",
        "crop": "Corn / Maize",
        "cause": "Puccinia sorghi fungus, spread by wind-blown spores",
        "severity_levels": {"Low": "Few rust pustules", "Medium": "Extensive pustules on leaves", "High": "Severe leaf damage, yield loss"},
        "organic_treatment": "Remove severely infected leaves. Improve air circulation.",
        "chemical_treatment": "Spray Propiconazole (1ml/L) or Mancozeb (2.5g/L).",
        "prevention": "Plant rust-resistant hybrids, early sowing, balanced fertilization.",
        "recovery_time": "2-3 weeks",
    },
    "Rice___Brown_spot": {
        "disease": "Brown Spot",
        "crop": "Rice",
        "cause": "Bipolaris oryzae fungus, nutrient deficiency (especially potassium)",
        "severity_levels": {"Low": "Small brown spots", "Medium": "Multiple spots merging", "High": "Severe grain discoloration"},
        "organic_treatment": "Apply potassium-rich organic manure. Seed treatment with Trichoderma.",
        "chemical_treatment": "Spray Carbendazim (1g/L) or Mancozeb (2.5g/L).",
        "prevention": "Balanced NPK fertilization, seed treatment, avoid water stress.",
        "recovery_time": "2-3 weeks with nutrient correction",
    },
    "Rice___Leaf_blast": {
        "disease": "Leaf Blast",
        "crop": "Rice",
        "cause": "Magnaporthe oryzae fungus, high nitrogen, humid conditions",
        "severity_levels": {"Low": "Diamond-shaped spots", "Medium": "Lesions expanding, some dead leaves", "High": "Neck blast, panicle damage"},
        "organic_treatment": "Reduce nitrogen. Apply Pseudomonas fluorescens (10g/L).",
        "chemical_treatment": "Spray Tricyclazole (0.6g/L) or Isoprothiolane (1.5ml/L).",
        "prevention": "Use resistant varieties, avoid excess N, maintain field drainage.",
        "recovery_time": "3-4 weeks",
    },
    "Healthy": {
        "disease": "No Disease Detected",
        "crop": "General",
        "cause": "Plant appears healthy.",
        "severity_levels": {"Low": "Healthy"},
        "organic_treatment": "No treatment needed. Continue good agricultural practices.",
        "chemical_treatment": "No treatment needed.",
        "prevention": "Continue balanced fertilization, proper irrigation, and pest monitoring.",
        "recovery_time": "N/A",
    },
}


# ── Government Schemes ───────────────────────────────────────────────────
GOVERNMENT_SCHEMES = [
    {
        "name": "PM-KISAN",
        "full_name": "Pradhan Mantri Kisan Samman Nidhi",
        "benefit": "₹6,000 per year in 3 installments",
        "eligibility": "All landholding farmer families",
        "website": "https://pmkisan.gov.in",
    },
    {
        "name": "PMFBY",
        "full_name": "Pradhan Mantri Fasal Bima Yojana",
        "benefit": "Crop insurance at subsidized premium",
        "eligibility": "All farmers growing notified crops",
        "website": "https://pmfby.gov.in",
    },
    {
        "name": "PM-KUSUM",
        "full_name": "Pradhan Mantri Kisan Urja Suraksha evam Utthan Mahabhiyan",
        "benefit": "Solar pump subsidy, solar panels on farm land",
        "eligibility": "Individual farmers, farmer groups, cooperatives",
        "website": "https://pmkusum.mnre.gov.in",
    },
    {
        "name": "Soil Health Card",
        "full_name": "Soil Health Card Scheme",
        "benefit": "Free soil testing and nutrient recommendations",
        "eligibility": "All farmers",
        "website": "https://soilhealth.dac.gov.in",
    },
    {
        "name": "e-NAM",
        "full_name": "National Agriculture Market",
        "benefit": "Online trading platform for agricultural commodities",
        "eligibility": "All farmers, traders, buyers",
        "website": "https://enam.gov.in",
    },
    {
        "name": "KCC",
        "full_name": "Kisan Credit Card",
        "benefit": "Short-term credit at 4% interest for crop cultivation",
        "eligibility": "All farmers, tenant farmers, sharecroppers",
        "website": "https://www.pmkisan.gov.in/KCC.aspx",
    },
]


# ── Indian States and Districts ──────────────────────────────────────────
INDIAN_STATES = {
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Tirupati", "Kakinada", "Rajahmundry", "Anantapur", "Kadapa"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Erode", "Vellore", "Thoothukudi", "Thanjavur"],
    "Karnataka": ["Bengaluru", "Mysuru", "Hubli-Dharwad", "Mangaluru", "Belagavi", "Davanagere", "Ballari", "Kalaburagi", "Shimoga", "Tumkur"],
    "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Palakkad", "Alappuzha", "Kannur", "Kottayam", "Malappuram"],
    "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Mahbubnagar", "Nalgonda", "Adilabad", "Medak", "Rangareddy"],
    "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Solapur", "Kolhapur", "Amravati", "Sangli", "Satara"],
    "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Rewa", "Satna", "Dewas", "Chhindwara"],
    "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Meerut", "Allahabad", "Bareilly", "Gorakhpur", "Aligarh", "Moradabad"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner", "Ajmer", "Bhilwara", "Alwar", "Sikar", "Sri Ganganagar"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Junagadh", "Gandhinagar", "Anand", "Nadiad"],
    "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Hoshiarpur", "Pathankot", "Moga", "Firozpur"],
    "Haryana": ["Gurgaon", "Faridabad", "Panipat", "Ambala", "Hisar", "Karnal", "Sonipat", "Rohtak", "Yamunanagar", "Kurukshetra"],
    "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Siliguri", "Asansol", "Bardhaman", "Malda", "Baharampur", "Habra", "Kharagpur"],
    "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga", "Purnia", "Arrah", "Begusarai", "Katihar", "Munger"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Balasore", "Baripada", "Bhadrak", "Jharsuguda"],
}

# ── Language Codes ────────────────────────────────────────────────────────
LANGUAGE_CODES = {
    "English": "en",
    "தமிழ்": "ta",
    "हिन्दी": "hi",
    "తెలుగు": "te",
    "മലയാളം": "ml",
}

LANGUAGE_TTS_CODES = {
    "en": "en",
    "ta": "ta",
    "hi": "hi",
    "te": "te",
    "ml": "ml",
}

LANGUAGE_WHISPER_CODES = {
    "en": "en",
    "ta": "ta",
    "hi": "hi",
    "te": "te",
    "ml": "ml",
}
